# JoinEffect by TonyDroidd

#Effect ID's

#SPEED = 1
#SLOWNESS = 2
#HASTE = 3
#SWIFTNESS = 3
#FATIGUE = 4
#MINING_FATIGUE = 4
#STRENGTH = 5
#JUMP = 8
#NAUSEA = 9
#CONFUSION = 9
#REGENERATION = 10
#DAMAGE_RESISTANCE = 11
#FIRE_RESISTANCE = 12
#WATER_BREATHING = 13
#INVISIBILITY = 14
#WEAKNESS = 18
#POISON = 19
#WITHER = 20
#HEALTH_BOOST = 21


EffectID: 1
